version: '3.7'
services:
  ethereum-signer:
    build: .
    ports:
      - "3001:3001"
    environment:
      - HL_PRIVATE_KEY=${HL_PRIVATE_KEY}
      - PORT=3001
      - NODE_ENV=production
    networks:
      - network_public

networks:
  network_public:
    external: true
