version: '3.3'
services:
  ethereum-signer:
    image: node:16-alpine
    command: >
      sh -c "
        mkdir -p /app &&
        cd /app &&
        npm init -y &&
        npm install express@4.18.2 ethers@5.7.2 &&
        echo \"
const express = require('express');
const { Wallet } = require('ethers');
const app = express();

const PORT = process.env.PORT;
const PRIVATE_KEY = process.env.HL_PRIVATE_KEY;

app.use(express.json());

app.get('/', (req, res) => {
  res.json({ status: 'Ethereum Signer Online' });
});

app.post('/sign', async (req, res) => {
  try {
    const { message } = req.body;
    if (!message) {
      return res.status(400).json({ error: 'Message is required' });
    }

    const wallet = new Wallet(PRIVATE_KEY);
    const signature = await wallet.signMessage(message);

    res.json({
      address: wallet.address,
      signature
    });
  } catch (error) {
    console.error('Signing error:', error);
    res.status(500).json({ error: error.message });
  }
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(\`Server running on port \${PORT}\`);
});
\" > server.js &&
        node server.js
      "
    ports:
      - "3001:3001"
    environment:
      - HL_PRIVATE_KEY=${HL_PRIVATE_KEY}
      - PORT=3001
