version: '3.3'
services:
  ethereum-signer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - HL_PRIVATE_KEY=${HL_PRIVATE_KEY}
      - PORT=3001
