version: '3.7'

services:
  ethereum-signer:
    build: .
    ports:
      - "3001:3001"
    environment:
      HL_PRIVATE_KEY: "fa4865d1detc...a59664e3e0d7"
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  network_public:
    external: true
